"""add Department

Revision ID: 13427fb8feb0
Revises: 816741424f24
Create Date: 2025-03-26 12:54:40.802718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13427fb8feb0'
down_revision = '816741424f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
